using Hcb.Rnd.Pwn.Domain.Entities.Experiments;
using Hcb.Rnd.Pwn.Infrastructure.Persistence.FluentApi.EntityTypeConfigurations.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


namespace Hcb.Rnd.Pwn.Infrastructure.Persistence.FluentApi.EntityTypeConfigurations.Experiments;

public class WashingMachinesConfiguration() : BaseConfiguration<WashingMachine>(primaryIdNeeded: true)
{

    public override void Configure(EntityTypeBuilder<WashingMachine> builder)
    {
        base.Configure(builder);

        builder.Property(p => p.Name)
               .IsRequired()
               .HasMaxLength(100)
               .HasComment("Describes the name of the washing machine. i.e: Miele - W 1935");

        builder.Property(p => p.Program)
           .IsRequired()
           .HasMaxLength(100)
           .HasComment("Describes the name of the washing machine program. i.e: Standard Cotton");

        builder.Property(p => p.Temperature)
              .IsRequired()
              .HasMaxLength(40)
              .HasComment("Describes the temperature of the selected washing machine program.");


        builder.Property(p => p.MainWashTime)
                .IsRequired()
                .HasComment("Describes the main washing time of the total wash.");

        builder.Property(p => p.TotalWashTime)
                .IsRequired()
                .HasComment("Describes the total washing time including pre- and post-'main wash time'");

        #region Hdp fileds

        builder.Property(p => p.ActiveFlag)
          .IsRequired()
          .HasMaxLength(1);

        builder.Property(p => p.DrainPumpEquipped)
          .HasMaxLength(1);

        builder.Property(p => p.LoadingType)
            .HasMaxLength(20);

        builder.Property(p => p.Manufacturer)
            .HasMaxLength(20);

        builder.Property(p => p.MaximumLoad)
            .HasMaxLength(80);

        builder.Property(p => p.NeedsHotWater)
            .HasMaxLength(1);

        builder.Property(p => p.ProgramListId)
           .HasMaxLength(40);

        builder.Property(p => p.UserSequence);

        builder.Property(p => p.CreatedDateInstrumentModel);

        builder.Property(p => p.ModifiedDateInstrumentModel);

        builder.Property(p => p.CreatedDateProgramList);

        builder.Property(p => p.ModifiedDateProgramList);

        builder.Property(p => p.IsInHdpDeleted)
            .IsRequired()
            .HasDefaultValue(false);

        #endregion

        builder.HasMany(pt => pt.ProductSetups)
               .WithOne(p => p.WashingMachine)
               .HasForeignKey(p => p.WashingMachineId)
               .OnDelete(DeleteBehavior.NoAction);

        builder.HasIndex(wm => new
        {
            wm.Name,
            wm.Program,
            wm.Temperature,
            wm.MainWashTime,
            wm.TotalWashTime,
            wm.ActiveFlag
        }).IsUnique();


        builder.HasData(
                            new WashingMachine { Id = 1, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, automatic plus", Temperature = "20", MainWashTime = 74, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 2, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, automatic plus", Temperature = "30", MainWashTime = 74, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 3, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, automatic plus", Temperature = "40", MainWashTime = 74, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 4, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton", Temperature = "20", MainWashTime = 87, TotalWashTime = 159, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 5, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton", Temperature = "30", MainWashTime = 87, TotalWashTime = 159, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 6, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton", Temperature = "40", MainWashTime = 87, TotalWashTime = 159, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 7, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton", Temperature = "60", MainWashTime = 108, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 8, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short", Temperature = "20", MainWashTime = 70, TotalWashTime = 99, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 9, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short", Temperature = "30", MainWashTime = 70, TotalWashTime = 99, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 10, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short", Temperature = "40", MainWashTime = 70, TotalWashTime = 99, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 11, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short", Temperature = "60", MainWashTime = 78, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 12, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "Standard Cotton", Temperature = "20", MainWashTime = 70, TotalWashTime = 117, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 13, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "Standard Cotton", Temperature = "30", MainWashTime = 70, TotalWashTime = 117, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 14, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "Standard Cotton", Temperature = "40", MainWashTime = 70, TotalWashTime = 117, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 15, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "Standard Cotton", Temperature = "60", MainWashTime = 62, TotalWashTime = 107, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 16, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "EasyCare", Temperature = "40", MainWashTime = 48, TotalWashTime = 76, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 17, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "EasyCare", Temperature = "60", MainWashTime = 53, TotalWashTime = 89, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 18, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "20", MainWashTime = 96, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 19, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "20", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 20, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "20", MainWashTime = 96, TotalWashTime = 165, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 21, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "20", MainWashTime = 57, TotalWashTime = 125, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 22, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "30", MainWashTime = 96, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 23, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "30", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 24, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "30", MainWashTime = 96, TotalWashTime = 165, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 25, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "30", MainWashTime = 57, TotalWashTime = 125, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 26, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "40", MainWashTime = 96, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 27, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "40", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 28, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "40", MainWashTime = 96, TotalWashTime = 165, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 29, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "40", MainWashTime = 57, TotalWashTime = 125, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 30, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "50", MainWashTime = 97, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 31, ProgramListId = "PL-2501-0014", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "50", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 32, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "50", MainWashTime = 97, TotalWashTime = 165, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 33, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "50", MainWashTime = 56, TotalWashTime = 125, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 34, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "60", MainWashTime = 82, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 35, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "60", MainWashTime = 62, TotalWashTime = 99, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 36, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "60", MainWashTime = 82, TotalWashTime = 136, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 37, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "60", MainWashTime = 62, TotalWashTime = 116, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 38, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "75", MainWashTime = 113, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 39, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "75", MainWashTime = 82, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 40, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "75", MainWashTime = 114, TotalWashTime = 166, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 41, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "75", MainWashTime = 82, TotalWashTime = 136, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 42, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton", Temperature = "90", MainWashTime = 113, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 43, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short", Temperature = "90", MainWashTime = 82, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 44, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, water+", Temperature = "90", MainWashTime = 114, TotalWashTime = 166, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 45, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton, short, water+", Temperature = "90", MainWashTime = 82, TotalWashTime = 136, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 46, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco", Temperature = "40", MainWashTime = 141, TotalWashTime = 179, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 47, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco, short", Temperature = "40", MainWashTime = 81, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 48, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco, water+", Temperature = "40", MainWashTime = 141, TotalWashTime = 196, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 49, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco, short, water+", Temperature = "40", MainWashTime = 81, TotalWashTime = 136, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 50, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco", Temperature = "60", MainWashTime = 141, TotalWashTime = 179, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 51, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco, short", Temperature = "60", MainWashTime = 81, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 52, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco, water+", Temperature = "60", MainWashTime = 141, TotalWashTime = 196, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 53, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "Standard Cotton Eco, short, water+", Temperature = "60", MainWashTime = 81, TotalWashTime = 136, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 54, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare", Temperature = "20", MainWashTime = 88, TotalWashTime = 112, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 55, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short", Temperature = "20", MainWashTime = 58, TotalWashTime = 82, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 56, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, water+", Temperature = "20", MainWashTime = 88, TotalWashTime = 122, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 57, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short, water+", Temperature = "20", MainWashTime = 58, TotalWashTime = 92, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 58, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare", Temperature = "30", MainWashTime = 88, TotalWashTime = 112, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 59, ProgramListId = "PL-2501-0018", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short", Temperature = "30", MainWashTime = 58, TotalWashTime = 82, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 60, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, water+", Temperature = "30", MainWashTime = 88, TotalWashTime = 122, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 61, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short, water+", Temperature = "30", MainWashTime = 58, TotalWashTime = 92, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 62, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare", Temperature = "40", MainWashTime = 88, TotalWashTime = 112, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 63, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short", Temperature = "40", MainWashTime = 58, TotalWashTime = 82, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 64, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, water+", Temperature = "40", MainWashTime = 88, TotalWashTime = 122, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 65, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short, water+", Temperature = "40", MainWashTime = 58, TotalWashTime = 92, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 66, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare", Temperature = "50", MainWashTime = 88, TotalWashTime = 115, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 67, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short", Temperature = "50", MainWashTime = 61, TotalWashTime = 85, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 68, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, water+", Temperature = "50", MainWashTime = 88, TotalWashTime = 125, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 69, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short, water+", Temperature = "50", MainWashTime = 61, TotalWashTime = 95, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 70, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare", Temperature = "60", MainWashTime = 91, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 71, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short", Temperature = "60", MainWashTime = 70, TotalWashTime = 94, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 72, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, water+", Temperature = "60", MainWashTime = 91, TotalWashTime = 129, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 73, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935Ecoline", Program = "EasyCare, short, water+", Temperature = "60", MainWashTime = 70, TotalWashTime = 104, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 74, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton", Temperature = "20", MainWashTime = 95, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 75, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton", Temperature = "30", MainWashTime = 95, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 76, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton", Temperature = "40", MainWashTime = 95, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 77, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton", Temperature = "60", MainWashTime = 85, TotalWashTime = 119, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 78, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton", Temperature = "Kalt", MainWashTime = 95, TotalWashTime = 149, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 79, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short", Temperature = "20", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 80, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short", Temperature = "30", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 81, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short", Temperature = "40", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 82, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short", Temperature = "60", MainWashTime = 60, TotalWashTime = 99, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 83, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short", Temperature = "Kalt", MainWashTime = 58, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 84, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, water+", Temperature = "20", MainWashTime = 95, TotalWashTime = 166, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 85, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, water+", Temperature = "30", MainWashTime = 95, TotalWashTime = 166, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 86, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, water+", Temperature = "40", MainWashTime = 95, TotalWashTime = 166, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 87, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, water+", Temperature = "60", MainWashTime = 80, TotalWashTime = 136, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 88, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, water+", Temperature = "Kalt", MainWashTime = 95, TotalWashTime = 166, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 89, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short water+", Temperature = "20", MainWashTime = 58, TotalWashTime = 126, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 90, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short water+", Temperature = "30", MainWashTime = 58, TotalWashTime = 126, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 91, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short water+", Temperature = "40", MainWashTime = 58, TotalWashTime = 126, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 92, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short water+", Temperature = "60", MainWashTime = 58, TotalWashTime = 116, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 93, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Standard Cotton, short water+", Temperature = "Kalt", MainWashTime = 58, TotalWashTime = 126, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 94, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1935", Program = "Minimum Iron (Easy Care)", Temperature = "40", MainWashTime = 75, TotalWashTime = 112, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 95, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1714", Program = "Standard Cotton", Temperature = "30", MainWashTime = 76, TotalWashTime = 124, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 96, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1714", Program = "Standard Cotton", Temperature = "40", MainWashTime = 76, TotalWashTime = 124, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 97, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1714", Program = "Standard Cotton", Temperature = "60", MainWashTime = 68, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 98, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1714", Program = "Standard Cotton", Temperature = "Kalt", MainWashTime = 76, TotalWashTime = 124, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 99, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1714", Program = "Standard Cotton, short", Temperature = "30", MainWashTime = 47, TotalWashTime = 90, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 100, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short", Temperature = "40", MainWashTime = 47, TotalWashTime = 90, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 101, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short", Temperature = "60", MainWashTime = 40, TotalWashTime = 85, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 102, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short", Temperature = "Kalt", MainWashTime = 47, TotalWashTime = 90, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 103, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, water+", Temperature = "30", MainWashTime = 76, TotalWashTime = 139, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 104, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, water+", Temperature = "40", MainWashTime = 76, TotalWashTime = 139, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 105, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, water+", Temperature = "60", MainWashTime = 68, TotalWashTime = 126, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 106, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, water+", Temperature = "Kalt", MainWashTime = 76, TotalWashTime = 139, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 107, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short, water+", Temperature = "30", MainWashTime = 44, TotalWashTime = 103, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 108, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short, water+", Temperature = "40", MainWashTime = 44, TotalWashTime = 103, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 109, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short, water+", Temperature = "60", MainWashTime = 41, TotalWashTime = 102, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 110, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Standard Cotton, short, water+", Temperature = "Kalt", MainWashTime = 44, TotalWashTime = 103, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 111, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name ="W1714", Program = "Easy Care", Temperature = "40", MainWashTime = 52, TotalWashTime = 79, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 112, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Whirlpool", LoadingType = "Front", Name = "WFWHEAW2", Program = "Normal, hot, extra fast, heavy", Temperature = "variable", MainWashTime = 28, TotalWashTime = 67, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 113, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Kenmore", LoadingType = "Front", Name = "80series", Program = "Normal, permanent press, ohne rinse", Temperature = "variable", MainWashTime = 8, TotalWashTime = 37, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 114, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Maytag", LoadingType = "Front", Name = "MVWC200BW1", Program = "Regular, one rinse, hot", Temperature = "variable", MainWashTime = 17, TotalWashTime = 42, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 115, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Haier", LoadingType = "Front", Name = "B7001Z71V", Program = "Frequently use", Temperature = "variable", MainWashTime = 11, TotalWashTime = 35, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 116, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "LG", LoadingType = "Front", Name = "WT7900HBA", Program = "Normal, warm, high, normal", Temperature = "variable", MainWashTime = 15, TotalWashTime = 30, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 117, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Toshiba", LoadingType = "Front", Name = "AW-F1005GBA", Program = "Regular", Temperature = "variable", MainWashTime = 12, TotalWashTime = 48, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 118, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Toshiba", LoadingType = "Front", Name = "AW-8460SB", Program = "Heavy", Temperature = "variable", MainWashTime = 9, TotalWashTime = 48, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 119, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1514", Program = "Easy Care / Delicate, Water+)", Temperature = "40", MainWashTime = 49, TotalWashTime = 89, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 120, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "W1734", Program = "Easy Care / Delicate, Water+)", Temperature = "40", MainWashTime = 49, TotalWashTime = 89, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 121, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "MABE", LoadingType = "Front", Name = "LMA70214VBAB0", Program = "Regular, one rinse", Temperature = "20", MainWashTime = 15, TotalWashTime = 28, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 122, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Whirlpool", LoadingType = "Front", Name = "8MWTW2081EN1", Program = "Regular, one rinse", Temperature = "20", MainWashTime = 15, TotalWashTime = 28, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 6, 14), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 6, 14) },
                            new WashingMachine { Id = 123, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short , water+", Temperature = "20", MainWashTime = 74, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 9, 18), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 9, 18) },
                            new WashingMachine { Id = 124, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short , water+", Temperature = "30", MainWashTime = 74, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 9, 18), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 9, 18) },
                            new WashingMachine { Id = 125, ProgramListId = "PL-2501-0017", ActiveFlag = 'Y', IsInHdpDeleted = false, DrainPumpEquipped = 'Y', MaximumLoad = "9999", NeedsHotWater = 'N', CreatedDateInstrumentModel = new DateTime(2024, 6, 14), ModifiedDateInstrumentModel = new DateTime(2024, 6, 14), CreatedDateProgramList = new DateTime(2024, 6, 14), ModifiedDateProgramList = new DateTime(2024, 6, 14), Manufacturer = "Miele", LoadingType = "Front", Name = "WCI360WTL", Program = "Standard Cotton, short , water+", Temperature = "40", MainWashTime = 74, TotalWashTime = 109, CreatedById = "SystemUser", CreatedAt = new DateTime(2024, 9, 18), UpdatedById = "SystemUser", UpdatedAt = new DateTime(2024, 9, 18) }



                        );

    }

}
